### ISSUE TITLE
Point to permanent URL

### ISSUE THREAD

**Issue by neubig** [inspired-co/eaas_client#2]
Currently we're pointing to a host-dependent URL, but it'd be nice to have a more permanent endpoint URL (at `inspiredco.ai`).
https://github.com/inspired-co/eaas_client/blob/main/eaas/client.py#L20

**Comment by pfliu-nlp** [comment]
yes, it's kinda ugly actually, do you have some off-the-peg idea for it, if not, I will try to figure it out.

**Comment by neubig** [comment]
I was thinking of setting up a url like `eaas-endpoint.inspiredco.ai` and forwarding it to the appropriate IP. We could discuss the details separately I guess.
